name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  commit_log:
    required: true
    description: 'commit log'
    default: ''
  style:
    required: true
    description: 'Decide what style you would like to use'
    default: 'angular'
  scopes:
    required: false
    description: 'ビルドに含めたいスコープをここに入れます'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
